name: charts_common
version: 0.9.1
description: A common library for charting packages.
author: Charts Team <charts_flutter@google.com>
homepage: https://github.com/google/charts

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  collection: ^1.14.13
  intl: ^0.16.1
  logging: any
  meta: ^1.2.4
  vector_math: ^2.0.8

dev_dependencies:
  mockito: ^4.1.3
  test: ^1.15.7
